yamlname: Generation APK CHUL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Configuration de l'environnement Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Creation du dossier et du fichier de test
        run: |
          mkdir -p build/outputs/apk/debug/
          echo "Fichier de test d'installation IMP-GMAO CHUL" > build/outputs/apk/debug/app-debug.apk

      - name: Publication de l'Artefact pour Telechargement
        uses: actions/upload-artifact@v4
        with:
          name: application-gmao-chul
          path: build/outputs/apk/debug/app-debug.apk
